version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_refraksi
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - uploads_data:/app/uploads  # Volume untuk menyimpan foto mata secara permanen
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_refraksi
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_kuat
      POSTGRES_DB: db_refraksi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  uploads_data: